openapi: 3.0.0
info:
  title: Courses
  description: Nexto Courses API.\n
  version: 0.0.1
paths:
  /courses:
    get:
      operationId: getAllCourses
      responses:
        "200":
          description: Get all courses
      x-swagger-router-controller: course
    post:
      operationId: postCourse
      requestBody:
        $ref: "#/components/requestBodies/Course"
      responses:
        "201":
          description: Course was correctly created
      x-swagger-router-controller: course
  "/courses/{id}":
    get:
      operationId: getCoursesById
      parameters:
        - name: id
          in: path
          description: Id of the course.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Course was fetched correctly
        "404":
          description: Course wasn't found
      x-swagger-router-controller: course
    put:
      operationId: putCoursesById
      parameters:
        - name: id
          in: path
          description: Id of the course.
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/Course"
      responses:
        "200":
          description: Course was replaced.
        "500":
          description: Internal server error
      x-swagger-router-controller: course
    delete:
      operationId: deleteCoursesById
      parameters:
        - name: id
          in: path
          description: Id of the course.
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/Course"
      responses:
        "204":
          description: Course was deleted
        "404":
          description: Course missing
      x-swagger-router-controller: course
    patch:
      operationId: patchCoursesById
      parameters:
        - name: id
          in: path
          description: Id of the course.
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/Course"
      responses:
        "200":
          description: Course was changed.
        "500":
          description: Internal server error
      x-swagger-router-controller: course
servers:
  - url: http://localhost:8080/
components:
  requestBodies:
    Course:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Course"
      description: Text of the course we want to save
  schemas:
    Course:
      type: object
      properties:
        text:
          type: string
          description: The course of the text